package org.usfirst.frc.team3786.robot.util;

public enum ButtonMappingType {
	WHEN_PRESSED,
	WHEN_RELEASED,
	WHEN_ACTIVE,
	WHEN_INACTIVE,
	WHILE_HELD,
	WHILE_ACTIVE,
	CANCEL_WHEN_ACTIVE,
	CANCEL_WHEN_PRESSED,
	TOGGLE_WHEN_ACTIVE,
	TOGGLE_WHEN_PRESSED;
}